databases-week-1-muhammet-emin-alper
HackYourHomework/databases-class41 pull request #11
Opened 2023-02-03 21:25 UTC by eminalpernl

2023-02-07 09:20 UTC, ArcoMul commented
Hi @eminalpernl, thank you for submitting the homework. Sadly I'm not able to run your code. A `package.json`/`package-lock.json` is missing, and you are using `import` in app.js, but as far as I know this is not supported without `webpack` or `vite` or something like that. Could you share how you start the application? I tried it with node 18.14.0 and 19.6.0

2023-02-08 12:11 UTC, ArcoMul requested changes
Hi @eminalpernl, thank you for proving the missing files! It's running fine now, only with exercise 1 I'm getting an SQL error, exercise 2 runs perfectly and looks good to me! :-)

2023-02-08 12:11 UTC, ArcoMul commented on Week1/Ex-1/app.js
> +CREATE TABLE IF NOT EXISTS Meeting (
Does exercise 1 execute correctly for you? I'm getting the following error:

```
code: 'ER_INVALID_DEFAULT',
  errno: 1067,
  sqlMessage: "Invalid default value for 'ending_time'",
  sqlState: '42000',
  index: 0,
  sql: '\n' +
    'CREATE TABLE IF NOT EXISTS Meeting (\n' +
    '  meeting_no INT AUTO_INCREMENT PRIMARY KEY,\n' +
    '  meeting_title VARCHAR(255) NOT NULL,\n' +
    '  starting_time TIMESTAMP NOT NULL,\n' +
    '  ending_time TIMESTAMP NOT NULL,\n' +
    '  room_no INT NOT NULL,\n' +
    '  FOREIGN KEY (room_no) REFERENCES Room(room_no)\n' +
    ')'
 ```

2023-02-08 12:11 UTC, ArcoMul commented on Week1/Ex-2/app.js
> +});
Very nice approach with the questions array, and querying and loggin the results in this manner!

2023-03-05 15:21 UTC, eminalpernl commented on Week1/Ex-1/app.js
> +CREATE TABLE IF NOT EXISTS Meeting (
I'm getting this when I run the Ex-1:

the database with the name of meetup deleted
the database with the name of meetup created successfully
Connected to "meetup"
Invitee table created successfully
Room table created successfully
Meeting table created successfully
Invitee table updated
Room table updated
Meeting table updated

2023-03-23 13:39 UTC, closed without merging