Databases-week-2-muhammet-emin-alper
HackYourHomework/databases-class41 pull request #20
Opened 2023-02-07 21:21 UTC by eminalpernl

2023-02-14 09:32 UTC, ArcoMul requested changes
Hi @eminalpernl, well done! The queries look good and execute well. I left some minor improvements in the comments below. Also:
- Make sure to not including homework of the week before in this weeks homework submissions. Files of week 1 are now also in this PR, it gets then a bit harder to read for me.
- It would also be great to name the different exercise with 1, 2, 3, 4... in front of the filename, then I know what to execute when. For example: `exercise-1-keys.js`.

2023-02-14 09:32 UTC, ArcoMul commented on Week2/keys.js
> +    database: 'week2DB',
When starting this script for the first time there is no database called `week2DB`, so it won't run.

2023-02-14 09:32 UTC, ArcoMul commented on Week2/keys.js
> +db.query('DROP DATABASE week2DB; CREATE DATABASE week2DB', (err, result)=>{
Here you only want to drop the database if it exists, please Google how to do this.

2023-02-14 09:32 UTC, ArcoMul commented on Week2/keys.js
> +db.query('USE week2DB',
Yea nice, if no database is defined when making the connection, we have to call USE to select the database

2023-02-14 09:32 UTC, ArcoMul commented on Week2/keys.js
> +    gender VARCHAR(10))ENGINE=InnoDB
1. ENUM is the perfect data type for gender
2. Why do you set the ENGINE here to InnoDB?

2023-02-14 09:32 UTC, ArcoMul commented on Week2/joins.js
> +        console.log(result);
`console.table` prints the query results nicely formatted

2023-02-14 09:32 UTC, ArcoMul commented on Week2/joins.js
> +    else {
No need for an else statement. Throwing an error stops the execution of the function anyway.

2023-02-14 09:32 UTC, ArcoMul commented on Week2/Aggregate_Functions.js
> +GROUP BY paper_title;
Better to `GROUP BY` paper_id, as paper_title could in theory be the same for two different papers, whereas paper_id is unique.

2023-02-14 09:32 UTC, ArcoMul commented on Week2/Aggregate_Functions.js
> +SELECT COUNT(research_Papers.paper_title) AS Number_of_papers
Same here, best to count `research_Papers.paper_id` as that is unique for sure, in case you end up with duplicate number you might want to look into using `DISTINCT`

2023-02-14 09:32 UTC, ArcoMul commented on Week2/Aggregate_Functions.js
> +`;
👌

2023-02-14 09:32 UTC, ArcoMul commented on Week2/Aggregate_Functions.js
> +GROUP BY authors.university;
:+1:

2023-02-14 09:32 UTC, ArcoMul commented on Week2/Aggregate_Functions.js
> +`
👏

2023-03-05 15:33 UTC, eminalpernl commented
> Hi @eminalpernl, well done! The queries look good and execute well. I left some minor improvements in the comments below. Also:
> 
> * Make sure to not including homework of the week before in this weeks homework submissions. Files of week 1 are now also in this PR, it gets then a bit harder to read for me.
> * It would also be great to name the different exercise with 1, 2, 3, 4... in front of the filename, then I know what to execute when. For example: `exercise-1-keys.js`.

2023-03-05 15:39 UTC, eminalpernl commented
> Hi Arco thanks for this valuable feedback. I made PR after I was switching a new branch. I don't know why all files are also being seen here.

2023-03-05 15:48 UTC, eminalpernl commented on Week2/keys.js
> +    database: 'week2DB',
I delete the statement of " database: 'week2DB' "

2023-03-05 15:50 UTC, eminalpernl commented on Week2/keys.js
> +db.query('DROP DATABASE week2DB; CREATE DATABASE week2DB', (err, result)=>{
`db.query('DROP DATABASE IF EXISTS week2DB; CREATE DATABASE week2DB', (err, result)=>{
    if (err) throw err;
        console.log(result)
});`

I change the code into this

2023-03-05 16:14 UTC, eminalpernl commented on Week2/keys.js
> +    gender VARCHAR(10))ENGINE=InnoDB
I change code like this:

`db.query(`CREATE TABLE authors (
    author_id INT AUTO_INCREMENT PRIMARY KEY,
    author_name VARCHAR(50),
    university VARCHAR(100),
    date_of_birth DATE,
    h_index INT,
    gender ENUM('M','F'));`,
    (err, result)=>{
        if(err) throw err;
        console.log(result);
        console.log('authors table created...')
});`

I set the engine InnoDB because I was getting an error, it was recommended in a website but I figured out that it is useless, I just deleted it.

2023-03-05 16:19 UTC, eminalpernl commented on Week2/joins.js
> +    else {
I added else statement in case there is no errors to throw. If there is no error it is gonna log the result to the console.

2023-03-05 16:30 UTC, eminalpernl commented on Week2/Aggregate_Functions.js
> +GROUP BY paper_title;
I changed this into "paper_id".

2023-03-05 16:32 UTC, eminalpernl commented on Week2/Aggregate_Functions.js
> +SELECT COUNT(research_Papers.paper_title) AS Number_of_papers
I changed "paper.title" into "paper_id".

2023-03-08 19:00 UTC, ArcoMul commented on Week2/joins.js
> +    else {
That makes sense, but still the else-statement is not necesarry. While if there is an error it will throw the error and the execution of the code in this arrow function will stop, and if there is no error it will skip the if-statement and just continue. So for clean code you can avoid the else statement, and just write the code which is in the else-statement underneath the if-statement

2023-03-08 19:01 UTC, ArcoMul approved these changes
Hi @eminalpernl thank you for the updates, your fixes look good :-) To clean up this PR with the files of the other weeks you can just check out the branch and delete the files which shouldn't be there, and commit the deletion of the files.

2023-03-23 13:39 UTC, closed without merging