Databases-week-3-muhammet-emin-alper
HackYourHomework/databases-class41 pull request #29
Opened 2023-02-14 20:39 UTC by eminalpernl

2023-02-22 10:48 UTC, ArcoMul requested changes
Hi @eminalpernl, well done! One part of the mongodb exercise still has a mistake. Also please clean up the pull request by removing the files from week 1 and week 2 from this pull request. Best is to always make a new branch every week. From the main branch of the repository. You can now make a new branch from the main branch, and maybe [`cherry-pick`](https://stackoverflow.com/questions/9339429/what-does-cherry-picking-a-commit-with-git-mean) the commits you made for Week 3 into that branch.

2023-02-22 10:48 UTC, ArcoMul commented on Week1/Ex-1/app.js
> +import { querier, insertData, connection } from './controllers.js';
Could you remove the files from the homework of week 1 and 2 from this pull request?

2023-03-05 17:30 UTC, eminalpernl commented on Week1/Ex-1/app.js
> +import { querier, insertData, connection } from './controllers.js';
Hi Arco sorry to respond late. I will be more carefull about deleting older files. Bu I just corrected the codes on earlier homework as you wanted. Could you take a look new version of homeworks.

2023-03-05 17:50 UTC, eminalpernl commented on Week3/homework/mongodb/seedDatabase.js
> +import data from "./data.json" assert { type: "json" };
to be able to add assert statement. I added assert statement to handle an error. It was recommended in a website but I dont really remmeber what kind of an error. Maybe I could add assert statment without changing "require" statement. But I did not wanted to boteher too much:)

2023-03-05 17:52 UTC, eminalpernl commented on Week3/homework/mongodb/seedDatabase.js
> +import data from "./data.json" assert { type: "json" };
I think error was like this:
(node:11782) ExperimentalWarning: Importing JSON modules is an experimental feature and might change at any time

2023-03-05 19:31 UTC, eminalpernl commented on Week3/homework/mongodb/index.js
> +    `Created season 9 episode 13 and the document got the id ${createOneListing.insertedID}`
Ahh yee!!! 
I just realized that I had written "insertedID" instead of "insertedId".

2023-03-08 19:04 UTC, ArcoMul approved these changes
Thank you for the fix @eminalpernl, also here, files which shouldn't be in this PR can just be deleted, shouldn't be too much work. I'm approving the homework though.

2023-03-23 13:39 UTC, closed without merging