Databases-Week-4_muhammet-emin-alper
HackYourHomework/databases-class41 pull request #40
Opened 2023-02-21 21:38 UTC by eminalpernl

2023-02-27 11:42 UTC, ArcoMul commented
Hi @eminalpernl, please remove the homework files of the other weeks out of this Pull Request

2023-03-05 19:33 UTC, eminalpernl commented
Hi Arco I went through all the Homeworks in this module.

2023-03-08 20:58 UTC, ArcoMul requested changes
Hi @eminalpernl, thank you for the updates! Assignment one looks good, besides the formatting of the file. Exercise 2 can be improved a bit. Also please in this case, remove all the files which shouldn't be in this pull request (the ones from the other homework weeks). It makes it easier for me to review, and is a neater way of working in general.

2023-03-08 20:58 UTC, ArcoMul commented on Week4/homework/ex1-aggregation/index.js
> +
Please format your code using Prettier, double linebreaks shouldn't be in the file

2023-03-08 20:58 UTC, ArcoMul commented on Week4/homework/ex2-transactions/index.js
> +        await accountsCollection.updateOne({ account_number: sender }, { $set: { balance: fromAccount.balance - amount, account_changes: fromAccountChanges } }, { session });
Please look into the `$inc` and `$push` parameters for `updateOne`. The code of this transaction can be shortened a lot using those features.

2023-03-23 13:39 UTC, closed without merging